# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juliannaspizzaapp', '0006_auto_20170722_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
